drop table thing cascade;
drop table block cascade;
drop table thing_breaks_block;
drop table thing_falls_from_bloc;
drop table biome cascade;
drop table biome_block cascade;
drop table thing_property cascade;
drop table mob cascade;
drop table mob_gives_thing cascade;
drop table mob_drops_thing cascade;
drop table craft_recipe cascade;
drop table baking_recipe;
drop table enchantment cascade;
drop table enchantment_recipe cascade;
drop table forging_recipe cascade;
drop table brewing_recipe cascade;
drop function getMaterials;
drop type thing_type;
drop type thing_type_lvl2;
drop sequence thing_seq;